---
- name: Deploy Flask App
  hosts: all
  become: True

  tasks:
    - name: Ensure Flask is installed
      pip:
        name: flask
        executable: pip3

    - name: Copy app.py
      copy:
        src: ../artifacts/app.py
        dest: /opt/flask-app/app.py

    - name: Restart Flask App
      systemd:
        name: flask-app
        state: restarted
